import { inject } from '@adonisjs/core'
import db from '@adonisjs/lucid/services/db'
import { DateTime } from 'luxon'

import {
  DischargeClosedException,
  DischargeNotFoundException,
  DischargeNotPlannedException,
  ShiftIdConflictException,
} from '#discharges/shared/discharge_exceptions'
import {
  ineligibleShiftResponsibleIssue,
  throwPreparationIssues,
} from '#discharges/shared/discharge_preparation_issues'
import { planPlannedShiftResources } from '#discharges/shared/planned_shift_resources'
import {
  findAddedShiftIssues,
  planAddedShiftSequences,
} from '#discharges/shared/planned_shift_rules'
import DischargePreparationRepository from '#discharges/shared/repositories/discharge_preparation_repository'
import DischargeRepository from '#discharges/shared/repositories/discharge_repository'
import { lockDischargeOpenToShifts } from '#discharges/shared/shift_discharge_guard'
import { isEligibleShiftResponsible } from '#users/shared/shift_responsible_eligibility'

export type AddPlannedShiftInput = {
  dischargeId: string
  /** Generated by the add form when it opens, and sent again by every retry of it. */
  id: string
  plannedStartAt: DateTime
  plannedEndAt: DateTime
  responsibleUserId: string
  truckIds: string[]
  warehouseDoorIds: string[]
  weighingAreaIds: string[]
}

@inject()
export default class AddPlannedShiftUseCase {
  constructor(
    private preparationRepository: DischargePreparationRepository,
    private dischargeRepository: DischargeRepository,
  ) {}

  /**
   * Adds a planned shift to a planned or active discharge in one transaction: its period, its
   * responsible, and on a planned discharge the trucks, warehouse doors, and weighing areas it starts
   * with.
   *
   * The discharge's lock serializes this with every other shift write and with a start, so the
   * period is judged on the shifts as they are at commit. A submission whose identity already names
   * a shift of this discharge is a replay of an addition that succeeded: it answers that shift
   * (`created: false`) before any status or rule, since the discharge may have started or closed
   * between the addition and its retry.
   *
   * An active discharge's resources are runtime changes, not preparation, so a selection sent for one
   * is a state conflict: the form that sent it was opened before the discharge started.
   */
  async handle(input: AddPlannedShiftInput) {
    const created = await db.transaction(async (client) => {
      const discharge = await lockDischargeOpenToShifts(
        this.preparationRepository,
        input.dischargeId,
        client,
      )

      if (await this.preparationRepository.findShiftIdentity(discharge.id, input.id, client)) {
        return false
      }
      if (discharge.status === 'CLOSED') {
        throw new DischargeClosedException()
      }
      const selectsResources =
        input.truckIds.length > 0 ||
        input.warehouseDoorIds.length > 0 ||
        input.weighingAreaIds.length > 0
      if (discharge.status !== 'PLANNED' && selectsResources) {
        throw new DischargeNotPlannedException()
      }

      const shifts = await this.preparationRepository.listShifts(discharge.id, client)
      const issues = findAddedShiftIssues(input, shifts)

      const users = await this.preparationRepository.lockUsers([input.responsibleUserId], client)
      const responsible = users.get(input.responsibleUserId.toLowerCase())
      if (!responsible || !isEligibleShiftResponsible(responsible)) {
        issues.push(ineligibleShiftResponsibleIssue('responsibleUserId'))
      }

      const resources =
        discharge.status === 'PLANNED'
          ? await planPlannedShiftResources(
              this.preparationRepository,
              {
                dischargeId: discharge.id,
                shiftId: input.id,
                truckIds: input.truckIds,
                warehouseDoorIds: input.warehouseDoorIds,
                weighingAreaIds: input.weighingAreaIds,
                now: DateTime.utc(),
              },
              client,
            )
          : null

      throwPreparationIssues([...issues, ...(resources?.issues ?? [])])
      if (
        resources?.trucks.kind === 'ISSUES' ||
        resources?.warehouseDoors.kind === 'ISSUES' ||
        resources?.weighingAreas.kind === 'ISSUES'
      ) {
        return false
      }

      const { sequence, sequences } = planAddedShiftSequences(shifts, input)
      const result = await this.preparationRepository.insertPlannedShift(
        {
          dischargeId: discharge.id,
          shiftId: input.id,
          sequence,
          plannedStartAt: input.plannedStartAt,
          plannedEndAt: input.plannedEndAt,
          responsibleUserId: input.responsibleUserId,
          sequences,
          warehouseDoors: { inserts: resources?.warehouseDoors.inserts ?? [] },
          weighingAreas: { inserts: resources?.weighingAreas.inserts ?? [] },
        },
        client,
      )
      if (result.kind === 'DUPLICATE_ID') {
        throw new ShiftIdConflictException()
      }

      if (resources && resources.trucks.inserts.length > 0) {
        await this.preparationRepository.writeShiftTruckSelection(
          {
            dischargeId: discharge.id,
            shiftId: input.id,
            deleteIds: [],
            inserts: resources.trucks.inserts,
          },
          client,
        )
      }

      return true
    })

    const discharge = await this.dischargeRepository.findDetail(input.dischargeId)
    if (!discharge) {
      throw new DischargeNotFoundException()
    }

    return { discharge, created }
  }
}
