/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Customers: () => import('#controllers/customers_controller'),
  Docks: () => import('#controllers/docks_controller'),
  Health: () => import('#controllers/health_controller'),
  Login: () => import('#controllers/login_controller'),
  Logout: () => import('#controllers/logout_controller'),
  Me: () => import('#controllers/me_controller'),
  TransportCompanies: () => import('#controllers/transport_companies_controller'),
  WarehouseDoors: () => import('#controllers/warehouse_doors_controller'),
  Warehouses: () => import('#controllers/warehouses_controller'),
  WeighingAreas: () => import('#controllers/weighing_areas_controller'),
}
