/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Health: () => import('#controllers/health_controller'),
  Login: () => import('#controllers/login_controller'),
  Logout: () => import('#controllers/logout_controller'),
  Me: () => import('#controllers/me_controller'),
}
