/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CustomerSchema extends BaseModel {
  static $columns = ['archiveComment', 'archivedAt', 'archivedByUserId', 'code', 'companyName', 'createdAt', 'id', 'reactivatedAt', 'reactivatedByUserId', 'reactivationComment', 'status', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare archiveComment: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedByUserId: string | null
  @column()
  declare code: string
  @column()
  declare companyName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare reactivationComment: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DischargeTruckAssignmentSchema extends BaseModel {
  static $columns = ['createdAt', 'dischargeId', 'id', 'registrationSnapshot', 'releasedAt', 'reservedAt', 'transportCompanyId', 'transportCompanyNameSnapshot', 'truckId', 'updatedAt'] as const
  $columns = DischargeTruckAssignmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dischargeId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare registrationSnapshot: string
  @column.dateTime()
  declare releasedAt: DateTime | null
  @column.dateTime()
  declare reservedAt: DateTime
  @column()
  declare transportCompanyId: string | null
  @column()
  declare transportCompanyNameSnapshot: string
  @column()
  declare truckId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DischargeSchema extends BaseModel {
  static $columns = ['createdAt', 'dockId', 'expectedStartAt', 'id', 'status', 'updatedAt', 'vesselComment', 'vesselImo', 'vesselName'] as const
  $columns = DischargeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dockId: string
  @column.dateTime()
  declare expectedStartAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vesselComment: string | null
  @column()
  declare vesselImo: string | null
  @column()
  declare vesselName: string
}

export class DockSchema extends BaseModel {
  static $columns = ['archiveComment', 'archivedAt', 'archivedByUserId', 'createdAt', 'id', 'latitude', 'longitude', 'name', 'reactivatedAt', 'reactivatedByUserId', 'reactivationComment', 'status', 'updatedAt'] as const
  $columns = DockSchema.$columns
  @column()
  declare archiveComment: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare name: string
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare reactivationComment: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductLotSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'description', 'dischargeId', 'expectedQuantityTonnes', 'id', 'productName', 'updatedAt'] as const
  $columns = ProductLotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string
  @column()
  declare description: string | null
  @column()
  declare dischargeId: string
  @column()
  declare expectedQuantityTonnes: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ShiftTruckSchema extends BaseModel {
  static $columns = ['createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'shiftId', 'truckId', 'updatedAt'] as const
  $columns = ShiftTruckSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare shiftId: string
  @column()
  declare truckId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ShiftWarehouseDoorSchema extends BaseModel {
  static $columns = ['createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'shiftId', 'updatedAt', 'warehouseDoorId'] as const
  $columns = ShiftWarehouseDoorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare shiftId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare warehouseDoorId: string
}

export class ShiftWeighingAreaSchema extends BaseModel {
  static $columns = ['createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'shiftId', 'updatedAt', 'weighingAreaId'] as const
  $columns = ShiftWeighingAreaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare shiftId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare weighingAreaId: string
}

export class ShiftSchema extends BaseModel {
  static $columns = ['createdAt', 'dischargeId', 'id', 'plannedEndAt', 'plannedStartAt', 'responsibleUserId', 'sequence', 'status', 'updatedAt'] as const
  $columns = ShiftSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dischargeId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare plannedEndAt: DateTime
  @column.dateTime()
  declare plannedStartAt: DateTime
  @column()
  declare responsibleUserId: string
  @column()
  declare sequence: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TransportCompanySchema extends BaseModel {
  static $columns = ['archiveComment', 'archivedAt', 'archivedByUserId', 'contactEmail', 'contactPhone', 'createdAt', 'id', 'name', 'reactivatedAt', 'reactivatedByUserId', 'reactivationComment', 'status', 'updatedAt'] as const
  $columns = TransportCompanySchema.$columns
  @column()
  declare archiveComment: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedByUserId: string | null
  @column()
  declare contactEmail: string | null
  @column()
  declare contactPhone: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare reactivationComment: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TruckSchema extends BaseModel {
  static $columns = ['archiveComment', 'archivedAt', 'archivedByUserId', 'capacityTonnes', 'createdAt', 'id', 'reactivatedAt', 'reactivatedByUserId', 'reactivationComment', 'registration', 'returnToServiceComment', 'returnedToServiceAt', 'returnedToServiceByUserId', 'status', 'suspendedAt', 'suspendedByUserId', 'suspensionComment', 'transportCompanyId', 'updatedAt', 'vehicleModel'] as const
  $columns = TruckSchema.$columns
  @column()
  declare archiveComment: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedByUserId: string | null
  @column()
  declare capacityTonnes: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare reactivationComment: string | null
  @column()
  declare registration: string
  @column()
  declare returnToServiceComment: string | null
  @column.dateTime()
  declare returnedToServiceAt: DateTime | null
  @column()
  declare returnedToServiceByUserId: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare suspendedAt: DateTime | null
  @column()
  declare suspendedByUserId: string | null
  @column()
  declare suspensionComment: string | null
  @column()
  declare transportCompanyId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vehicleModel: string | null
}

export class UserActivationTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'updatedAt', 'userId'] as const
  $columns = UserActivationTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['accessStatus', 'activatedAt', 'activatedByUserId', 'cancelledAt', 'cancelledByUserId', 'createdAt', 'deactivatedAt', 'deactivatedByUserId', 'email', 'firstName', 'id', 'invitedAt', 'invitedByUserId', 'lastName', 'password', 'passwordRenewalRequiredAt', 'reactivatedAt', 'reactivatedByUserId', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare accessStatus: string
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column()
  declare activatedByUserId: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deactivatedAt: DateTime | null
  @column()
  declare deactivatedByUserId: string | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare invitedAt: DateTime | null
  @column()
  declare invitedByUserId: string | null
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime()
  declare passwordRenewalRequiredAt: DateTime | null
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WarehouseDoorProductLotAssignmentSchema extends BaseModel {
  static $columns = ['createdAt', 'dischargeId', 'effectiveFrom', 'effectiveTo', 'id', 'productLotId', 'updatedAt', 'warehouseDoorId'] as const
  $columns = WarehouseDoorProductLotAssignmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dischargeId: string
  @column.dateTime()
  declare effectiveFrom: DateTime
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productLotId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare warehouseDoorId: string
}

export class WarehouseDoorSchema extends BaseModel {
  static $columns = ['archiveComment', 'archivedAt', 'archivedByUserId', 'createdAt', 'id', 'latitude', 'longitude', 'name', 'reactivatedAt', 'reactivatedByUserId', 'reactivationComment', 'status', 'updatedAt', 'warehouseId'] as const
  $columns = WarehouseDoorSchema.$columns
  @column()
  declare archiveComment: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare name: string
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare reactivationComment: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare warehouseId: string
}

export class WarehouseFootprintPointSchema extends BaseModel {
  static $columns = ['latitude', 'longitude', 'position', 'warehouseId'] as const
  $columns = WarehouseFootprintPointSchema.$columns
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare position: number
  @column({ isPrimary: true })
  declare warehouseId: string
}

export class WarehouseSchema extends BaseModel {
  static $columns = ['archiveComment', 'archivedAt', 'archivedByUserId', 'createdAt', 'id', 'name', 'reactivatedAt', 'reactivatedByUserId', 'reactivationComment', 'status', 'updatedAt'] as const
  $columns = WarehouseSchema.$columns
  @column()
  declare archiveComment: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare reactivationComment: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WeighingAreaSchema extends BaseModel {
  static $columns = ['archiveComment', 'archivedAt', 'archivedByUserId', 'createdAt', 'id', 'latitude', 'longitude', 'name', 'reactivatedAt', 'reactivatedByUserId', 'reactivationComment', 'status', 'updatedAt'] as const
  $columns = WeighingAreaSchema.$columns
  @column()
  declare archiveComment: string | null
  @column.dateTime()
  declare archivedAt: DateTime | null
  @column()
  declare archivedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare latitude: number
  @column()
  declare longitude: number
  @column()
  declare name: string
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare reactivationComment: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
