/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class UserSchema extends BaseModel {
  static $columns = ['accessStatus', 'activatedAt', 'activatedByUserId', 'cancelledAt', 'cancelledByUserId', 'createdAt', 'deactivatedAt', 'deactivatedByUserId', 'email', 'firstName', 'id', 'invitedAt', 'invitedByUserId', 'lastName', 'password', 'reactivatedAt', 'reactivatedByUserId', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare accessStatus: string
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column()
  declare activatedByUserId: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deactivatedAt: DateTime | null
  @column()
  declare deactivatedByUserId: string | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare invitedAt: DateTime | null
  @column()
  declare invitedByUserId: string | null
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string | null
  @column.dateTime()
  declare reactivatedAt: DateTime | null
  @column()
  declare reactivatedByUserId: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
